/*
    날짜 : 2025.07.15.
    이름 : 강민철
    내용 : 3장 제약조건
*/

-- 실습하기
CREATE TABLE USER2 (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    NAME    VARCHAR2(20),
    HP      CHAR(13),
    AGE     NUMBER(2)
);

-- primary key(기본키)는 중복 허용 안 됨.
INSERT INTO USER2 VALUES ('A101', '김유신', '010-1234-1111', 23);
INSERT INTO USER2 VALUES ('A101', '김춘추', '010-1234-2222', 21);

// 실습하기 2-2
create table user3 (
    user_id varchar2(20) primary key,
    name    varchar2(20),
    hp      char(13) unique,
    age     number(3)
    );

insert into user3 values ('a101', '김유신', '010-1234-1111', 23);
insert into user3 values ('a102', '김춘추', '010-1234-2222', 21);

// 실습하기 2-3
CREATE TABLE PARENT (
    pid varchar2(20) primary key,
    name varchar2(20),
    hp char(13) unique
);

create table child (
    CID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20),
    HP CHAR(13) UNIQUE,
    PARENT VARCHAR2(20),
    FOREIGN KEY (PARENT) REFERENCES PARENT (PID)
);

INSERT INTO PARENT VALUES ('P101', '김서현', '010-1234-1001');
INSERT INTO PARENT VALUES ('P102', '이성계', '010-1234-1002');
INSERT INTO PARENT VALUES ('P103', '신사임당', '010-1234-1003');

INSERT INTO CHILD VALUES ('C101', '김유신', '010-1234-2001', 'P101');
INSERT INTO CHILD VALUES ('C102', '이방우', '010-1234-2002', 'P102');
INSERT INTO CHILD VALUES ('C103', '이방원', '010-1234-2003', 'P102');
INSERT INTO CHILD VALUES ('C104', '이이', '010-1234-2004', 'P103');
-- 부모 테이블에 P105에 해당하는 값이 없기 때문에 참조 무결성 제약조건 위배
INSERT INTO CHILD VALUES ('C105', '김철수', '010-1234-2005', 'P105');

-- 실습하기 2-4
CREATE TABLE USER4 (
    NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    AGE NUMBER(2) DEFAULT 1,
    ADDR VARCHAR2(255)
);

INSERT INTO USER4 VALUES ('김유신', 'M', 23, '김해시');
INSERT INTO USER4 VALUES ('김춘추', 'M', 21, '경주시');
INSERT INTO USER4 (NAME, GENDER, ADDR) VALUES ('신사임당', 'F', '강릉시');
INSERT INTO USER4 (NAME, GENDER) VALUES ('이순신', 'M');
INSERT INTO USER4 (NAME, AGE) VALUES ('정약용', 33); -- 성별은 NOT NULL(반드시 입력해야함)

-- 실습하기 2-4
CREATE TABLE USER5 (
    NAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) NOT NULL CHECK(GENDER IN('M', 'F')),
    AGE INT DEFAULT 1 CHECK(AGE > 0 AND AGE < 100),
    ADDR VARCHAR2(255)
    );

INSERT INTO USER5 VALUES ('김유신', 'M', 23, '김해시');
INSERT INTO USER5 VALUES ('김춘추', 'M', 21, '경주시');
INSERT INTO USER5 (NAME, GENDER, ADDR) VALUES ('신사임당', 'F', '강릉시');
INSERT INTO USER5 (NAME, GENDER) VALUES ('이순신', 'M');
INSERT INTO USER5 (NAME, AGE) VALUES ('정약용', 33);

-- 실습하기 2-5 : IDENTITY
create table user7 (
    id number GENERATED by default as identity primary key,
    name varchar2(20),
    age number,
    email varchar2(100)
);

INSERT INTO USER7 (NAME, AGE, EMAIL) VALUES ('김유신', 25, 'kim@gmail.com');
INSERT INTO USER7 (NAME, AGE, EMAIL) VALUES ('장보고', 35, 'jang@gmail.com');
INSERT INTO USER7 (NAME, AGE, EMAIL) VALUES ('이순신', 45, 'lee@gmail.com');
    
select * from user7;