/*
    날짜 : 2025.07.18.
    이름 : 강민철
    내용 : SQL 연습문제
*/

-- 실습 1-2
create table Customer (
    CID     varchar2(20) primary key,
    name    varchar2(20) not null,
    hp      char(13) unique,
    address varchar2(200),
    RDATE   date not null
    );
    
create table Product (
    pno     number(4) primary key,
    pname   varchar2(30) not null,
    stock   number default 0 not null,
    price   number,
    company nvarchar2(20) not null
);

create table Orders (
    ord_no      number generated by default as identity not null,
    ord_cid     varchar2(20) not null,
    ord_pno     number(4) not null,
    ord_cnt     number default 1 not null,
    ord_date    date not null
);

-- 실습 1-3
insert all
    into customer values ('c101', '김유신', '010-1234-1001', '김해시 봉황동', '2022-01-01')
    into customer values ('c102', '김춘추', '010-1234-1002', '경주시 보문동', '2022-01-02')
    into customer values ('c103', '장보고', '010-1234-1003', '완도군 청산면', '2022-01-03')
    into customer values ('c104', '강감찬', '010-1234-1004', '김해시 봉황동', '2022-01-04')
select * from dual;

insert into customer (cid, name, rdate) values ('c105','이성계','2022-01-05');

insert all
    into customer values ('c106','정철','010-1234-1006','경기도 용인시','2022-01-06')
    into customer (cid,name,rdate) values ('c107','허준','2022-01-07')
    into customer values ('c108','이순신','010-1234-1008','서울시 영등포구','2022-01-08')
    into customer values ('c109','송상현','010-1234-1009','부산시 동래구','2022-01-09')
    into customer values ('c110','정약용','010-1234-1010','경기도 광주시','2022-01-10')
select * from dual;

insert all
    into product values (1,'새우깡',5000,1500,'농심')
    into product values (2,'초코파이',2500,2500,'오리온')
    into product values (3,'포카칩',3600,1700,'오리온')
    into product values (4,'양파링',1250,1800,'농심')
    into product (pno,pname,stock,company) values (5,'죠리퐁',2200,'크라운')
    into product values (6,'마가렛트',3500,3500,'롯데')
    into product values (7,'뿌셔뿌셔',1650,1200,'오뚜기')
select * from dual;

insert all
    into orders values (1,'c102',3,2,'2022-07-01 13:15:10')
    into orders values (2,'c101',4,1,'2022-07-01 14:16:11')
    into orders values (3,'c108',1,1,'2022-07-01 17:23:18')
    into orders values (4,'c109',6,5,'2022-07-02 10:46:36')
    into orders values (5,'c102',2,1,'2022-07-03 09:15:37')
    into orders values (6,'c101',7,3,'2022-07-03 12:35:12')
    into orders values (7,'c110',1,2,'2022-07-03 16:55:36')
    into orders values (8,'c104',2,4,'2022-07-04 14:23:23')
    into orders values (9,'c102',1,3,'2022-07-04 21:54:34')
    into orders values (10,'c107',6,1,'2022-07-05 14:21:03')
select * from dual;

-- 실습 1-4
select * from customer;

-- 실습 1-5
select cid, name, hp from customer;

-- 실습 1-6
select * from product;

-- 실습 1-7
select company from product;

-- 실습 1-8
select distinct company from product;

-- 실습 1-9
select pname,price from product;

-- 실습 1-10
select pname,price+500 as "조정단가" from product;

-- 실습 1-11
select pname,stock,price from product where company = '오리온';

-- 실습 1-12
select ord_pno,ord_cnt,ord_date from orders where ord_cid = 'c102';

-- 실습 1-13
select ord_pno,ord_cnt,ord_date from orders where ord_cid = 'c102' and ord_cnt >= 2;

-- 실습 1-14
select * from product where price between 1000 and 2000;

-- 실습 1-15
select cid,name,hp,address from customer where name like '김%';

-- 실습 1-16
select cid,name,hp,address from customer where name like '__';

-- 실습 1-17
select * from customer where hp is null;

-- 실습 1-18
select * from customer where address is not null;

-- 실습 1-19
select * from customer order by rdate desc;

-- 실습 1-20
select * from orders where ord_cnt >=3 order by ord_cnt desc, ord_pno asc;

-- 실습 1-21
select round(avg(price),4) as "AVG(PRICE)" from product;

-- 실습 1-22
select sum(stock) as "재고량 합계" from product where company='농심';

-- 실습 1-23
select count(cid) as 고객수 from customer;

-- 실습 1-24
select count(distinct company) as "제조업체 수" from product;

-- 실습 1-25
select ord_pno as "주문 상품번호",sum(ord_cnt) as "총 주문량" from orders group by ord_pno order by ord_pno;

-- 실습 1-26
select company as 제조업체, count(*) as 제품수, max(price) as 최고가 from product
group by company order by company;

-- 실습 1-27
select company as 제조업체, count(*) as 제품수, max(price) as 최고가 from
product group by company having count(*) >= 2;

-- 실습 1-28
select ord_pno, ord_cid, sum(ord_cnt) as "총 주문수량" from orders
group by ord_pno, ord_cid order by ord_pno;

-- 실습 1-29
select ord_cid, pname from orders a
join product b on a.ord_pno = b.pno
where ord_cid = 'c102';

-- 실습 1-30
select ord_cid, name, pname, ord_date from orders a
join customer b on a.ord_cid = b.cid
join product c on a.ord_pno = c.pno
where ord_date like '%-07-03%';