/* 
    날짜 : 2025.07.23.
    이름 : 강민철
    내용 : SQL 연습문제4
*/

-- 실습 4-1
alter session set "_oracle_script"=true;
create user library identified by 1234;
grant connect, resource, unlimited tablespace to library;

-- 실습 4-2
create table member (
    member_id   number(4) primary key,
    name        varchar2(40) not null,
    address     varchar2(100),
    hp          char(13) unique,
    join_date   date not null
);

create table Book (
    book_id     number(5) primary key,
    title       varchar2(50) not null,
    author      varchar2(40) not null,
    publisher   varchar2(40) not null,
    available   char(1),
    reg_date    date not null
);

create table loan (
    loan_id     number generated by default as identity primary key,
    member_id   number(4) not null,
    foreign key (member_id)  references member(member_id),
    book_id     number(5) not null,
    foreign key (book_id)    references Book(book_id),
    loan_date   date,
    return_date date,
    actual_date date
);

-- 실습 4-3
insert all
    into member values (1001,'김유신','서울특별시 강남구 역삼동','010-1234-1001','2024-01-10 09:15:00')
    into member values (1002,'김춘추','대전광역시 유성구 장대동','010-1234-1002','2024-02-14 14:30:45')
    into member values (1003,'장보고','대구광역시 수성구 반월동','010-1234-1003','2024-03-01 11:05:20')
    into member values (1004,'강감찬','부산광역시 금정구 부곡동','010-1234-1004','2024-03-22 16:40:00')
    into member values (1005,'이순신','광주광역시 광산구 우산동','010-1234-1005','2024-04-10 08:50:10')
select 1 from dual;

insert all
    into book values (10001,'태백산맥','조정래','문학수첩','Y','2014-01-10 09:15:00')
    into book values (10002,'데미안','헤르만 헤세','민음사','N','2014-02-14 14:30:45')
    into book values (10003,'토지','박경리','문학사상사','Y','2014-03-01 11:05:20')
    into book values (10004,'명품 자바 프로그래밍','제임스 고슬링','한빛출판사','Y','2014-03-22 16:40:00')
    into book values (10005,'로미오와 줄리엣','세익스피어','열린책들','N','2014-04-10 08:50:10')
    into book values (10006,'삼국지','나관중','민음사','Y','2014-04-05 09:12:02')
    into book values (10007,'칼의 노래','김훈','문학동네','Y','2014-06-10 12:53:17')
    into book values (10008,'데이터베이스','래리 엘리슨','한빛출판사','N','2014-05-23 10:13:09')
    into book values (10009,'Linux 운영체제','리누스 토발즈','한빛출판사','Y','2014-03-11 11:23:43')
    into book values (10010,'어린 왕자','생텍쥐베리','열린책들','Y','2014-05-13 15:27:21')
select 1 from dual;

insert into loan (member_id,book_id,loan_date,return_date,actual_date) values(1001,10002,'2024-03-01 10:02:31','2024-03-15 10:02:31','2024-03-13 09:44:19');
insert into loan (member_id,book_id,loan_date,return_date,actual_date) values(1002,10004,'2024-03-05 15:10:02','2024-03-19 15:10:02','2024-03-12 17:12:30');
insert into loan (member_id,book_id,loan_date,return_date) values(1003,10008,'2024-04-01 11:01:12','2024-04-15 11:01:12');
insert into loan (member_id,book_id,loan_date,return_date,actual_date) values(1002,10001,'2024-04-10 14:32:01','2024-04-24 14:32:01','2024-04-22 13:56:32');
insert into loan (member_id,book_id,loan_date,return_date) values(1005,10004,'2024-04-15 16:24:21','2024-04-29 16:24:21');
insert into loan (member_id,book_id,loan_date,return_date,actual_date) values(1004,10006,'2024-05-01 09:12:09','2024-05-15 09:12:09','2024-05-14 09:21:27');
insert into loan (member_id,book_id,loan_date,return_date,actual_date) values(1001,10007,'2024-05-03 13:51:07','2024-05-19 13:51:07','2024-05-16 14:05:10');
insert into loan (member_id,book_id,loan_date,return_date) values(1003,10009,'2024-06-01 11:15:43','2024-06-15 11:15:43');
insert into loan (member_id,book_id,loan_date,return_date) values(1004,10004,'2024-06-02 12:30:52','2024-06-16 12:30:52');
insert into loan (member_id,book_id,loan_date,return_date) values(1002,10008,'2024-06-05 10:06:17','2024-06-19 10:06:17');

-- 실습 4-4
select member_id,name,hp,address from member;

-- 실습 4-5
select title,author from book;

-- 실습 4-6
select name,address from member where substr(address,1,2)='부산';

-- 실습 4-7
select title from book where available='Y';

-- 실습 4-8
select * from book where book_id=10005;

-- 실습 4-9
select member_id,name,hp from member where member_id=1002;

-- 실습 4-10
select title from book where substr(reg_date,1,7)='2014-03';
select title from book where reg_date between '2014-03-01' and '2014-03-31';
select title from book where reg_date like '2014-03%';

-- 실습 4-11
select title,author,publisher from book where publisher='민음사';

-- 실습 4-12
select loan_id,member_id,book_id from loan where actual_date is null;

-- 실습 4-13
select * from member where name like '김%';

-- 실습 4-14
select name,address from member where substr(address,1,2) in ('부산','대구');
select name,address from member where address like '부산%' or address like '대구%';

-- 실습 4-15
select book_id,title from book where book_id in (10003,10006);
select book_id,title from book where book_id=10003 or book_id=10006;

-- 실습 4-16
select title,author from book where author in ('조정래','박경리');

-- 실습 4-17
select name,join_date from member where join_date < '2024-04-01';

-- 실습 4-18
select loan_id,member_id,book_id,loan_date from loan where loan_date > '2024-05-01';

-- 실습 4-19
select title,author,publisher from book where available='N';

-- 실습 4-20
select * from book where title like '%자바%';

-- 실습 4-21
select name,hp from member where hp<>'010-1234-1003';

-- 실습 4-22
select loan_id,member_id,book_id from loan where return_date < '2024-03-20';

-- 실습 4-23
select * from member order by name asc;

-- 실습 4-24
select title,reg_date from book order by reg_date desc;

-- 실습 4-25
select title from book 
order by title asc 
fetch next 3 rows only;

-- 실습 4-26
select * from member
order by join_date desc
fetch next 1 rows only;

-- 실습 4-27
select loan_id,loan_date from loan
order by loan_date asc
fetch next 2 rows only;

-- 실습 4-28
select count(*) from member;

-- 실습 4-29
select count(*) from book;

-- 실습 4-30
select count(*) from book where available='Y';

-- 실습 4-31
select publisher,count(*) as 출판_도서수 
from book 
group by publisher;

-- 실습 4-32
select count(*) from loan
where substr(loan_date,1,4)='2024';

-- 실습 4-33
select member_id,count(*) as 대출_도서수
from loan group by member_id;

-- 실습 4-34
select book_id,count(*) as 대출횟수
from loan group by book_id;

-- 실습 4-35
select member_id,count(*) as 회원_대출건수
from loan group by member_id
having count(*)>=2;

-- 실습 4-36
select book_id,count(*) as 도서_대출건수
from loan group by book_id
having count(*)>=2;

-- 실습 4-37
select
    m.member_id,
    m.name,
    b.book_id,
    b.title,
    l.loan_date
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id;

-- 실습 4-38
select 
    name,
    count(*) as 대출건수
from member m
join loan l on m.member_id=l.member_id
group by m.name having count(*)>=3;

-- 실습 4-39
select 
    l.loan_id,
    m.name,
    b.title,
    l.loan_date
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where loan_date<'2024-05-01';

-- 실습 4-40
select title
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where name='김유신';

-- 실습 4-41
select name
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where title='태백산맥';

-- 실습 4-42
select name,title
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where name='김춘추' order by title asc;

-- 실습 4-43
select title,name
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where loan_date like '2024-04%';

-- 실습 4-44
select name,title
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where actual_date is null;

-- 실습 4-45
select name,title
from member m
join loan l on m.member_id=l.member_id
join book b on l.book_id=b.book_id
where author='조정래';

-- 실습 4-46
select b.book_id,title
from loan l
right join book b on l.book_id=b.book_id
where loan_date is null;
select b.book_id,title
from book b
left join loan l on l.book_id=b.book_id
where loan_date is null;

-- 실습 4-47
select name,count(distinct book_id) as 총_건수
from member m
join loan l on m.member_id=l.member_id
group by name, l.member_id
order by count(distinct book_id) desc;

-- 실습 4-48
select name from member where member_id=(
    select 
        member_id 
    from loan 
    group by member_id 
    order by count(*) desc
    fetch first 1 rows only
);

-- 실습 4-49
select title from book where publisher = (
    select publisher from book where title='데이터베이스'
) and title <> '데이터베이스';

-- 실습 4-50
select name from member where member_id in (
    select member_id from loan where book_id=10004
);